org: jonlazariniaws
app: auction-aws
service: auction-aws
useDotenv: true

plugins:
  - serverless-bundle
  - serverless-pseudo-parameters

provider:
  lambdaHashingVersion: 20201221
  name: aws
  runtime: nodejs14.x
  memorySize: 256
  stage: ${env:SLS_AWS_STAGE, 'dev'}
  region: eu-west-1
  
functions:
  createAuction:
    handler: src/handlers/createAuction.handler
    events:
      - http:
          method: POST
          path: /auction
custom:
  bundle:
    linting: false
